### ISSUE TITLE
conversion issue

### ISSUE THREAD

**Issue by fabianje** [ANYbotics/pointmatcher-ros#11]
https://github.com/ANYbotics/pointmatcher-ros/blob/4b34a3d4f4f49699a764489e8b6a996ee18ff7ab/pointmatcher_ros/src/StampedPointCloud.cpp#L174

After adding a get() to the end of expression, the package compiles. Otherwise, it does not.

**Comment by remod** [comment]
Are you using our libpointmatcher fork? I think they updated from raw to shared ptrs.

**Comment by marco-tranzatto** [comment]
@remod  your fork from libpointmatcher should be installed via apt, right? or cloned and installed via source?

**Comment by fabianje** [comment]
You are absolutely right. I cloned the wrong repo.

**Comment by remod** [comment]
@marco-tranzatto You could do either or :)
