### ISSUE TITLE
Update of version number

### ISSUE THREAD

**Issue by wxmerkt** [ANYbotics/pointmatcher-ros#22]
Hi, 
We've noticed that many API breaking changes (including a namespace renaming) were carried out and the version number of the package has remained at 1.3.0 for 2 years. We'd like to use the version number to make our code work with both versions using if-guards (to work on 20.07.2 on Melodic and 20.12.1 on Noetic simultaneously).

Could you please change the version number and re-package the binary?

Thanks,
Wolfgang

cc: @benoit-robotics

**Comment by wxmerkt** [comment]
Friendly ping - this issue is still present on Release 21.01.1. Could you please increment the version number to match the API changes? Thanks! :-)

**Comment by YoshuaNava** [comment]
Hi @wxmerkt,
Thank you for reporting this issue.

I'll quickly discuss it internally and submit a fix.

Best,
Yoshua

**Comment by wxmerkt** [comment]
Thanks for the swift action! :-)

**Comment by YoshuaNava** [comment]
@wxmerkt A fix has been merged, commit 1b3e35c32a517746933677e55910090509f55d82

Let me know if this solves the issue on your side.

**Comment by wxmerkt** [comment]
Thanks Yoshua. This should fix the issue once the new binaries are out via the Anymal Research PPAs.
